on:
  push: {}
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt;
    
    - name: Validate dependencies
      run: |
        pip check
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
    - name: Set Notification Title
      id: set-title
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
        else
          echo "PR_TITLE=Push to branch '${{ github.ref }}'" >> $GITHUB_ENV
        fi
    
    - name: Send Success Notification to Discord (Building)
      if: success()
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{
          \"content\": \"CI Build Success: The build completed successfully for $PR_TITLE!\"
        }" $DISCORD_WEBHOOK_URL

    - name: Send Failure Notification to Discord (Building)
      if: failure()
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{
          \"content\": \"CI Build Failed: Something went wrong during the build for $PR_TITLE.\"
        }" $DISCORD_WEBHOOK_URL